Update oc-lab

diff --git a/oc-lab b/oc-lab
--- a/oc-lab
+++ b/oc-lab
@@ -118,7 +118,7 @@ generate_network_xml() {
     <host ip='10.101.194.2'>
       <hostname>quay.${cluster_name}.${domain}</hostname>
     </host>
-    <host ip='10.101.194.20'>
+    <host ip='10.101.194.5'>
       <hostname>api.${cluster_name}.${domain}</hostname>
     </host>
   </dns>
@@ -130,7 +130,7 @@ generate_network_xml() {
   <ip address='10.101.194.2' netmask='255.255.255.0'/>
   <ip address='10.101.194.3' netmask='255.255.255.0'/>
   <dnsmasq:options>
-    <dnsmasq:option value='address=/.apps.${cluster_name}.${domain}/10.101.194.20'/>
+    <dnsmasq:option value='address=/.apps.${cluster_name}.${domain}/10.101.194.10'/>
   </dnsmasq:options>
 </network>
 EOF
@@ -325,14 +325,22 @@ destroy_cluster() {
 }
 
 generate_agent_config() {
-  local base_ip="10.101.194"
+  local base_ip_test=$(getent hosts "api.${cluster_name}.${base_domain}" | awk '{ print $1 }')
+
+  # Check if the base_ip is empty or not resolved
+  if [ -z "${base_ip_test}" ]; then
+    echo "Failed to resolve DNS for api.${cluster_name}.${base_domain}. Please verify DNS configuration."
+    exit 1
+  fi
+
+  local base_ip=$(echo "${base_ip_test}" | awk -F '.' '{print $1"."$2"."$3""}')
+
   echo "apiVersion: v1alpha1"
   echo "kind: AgentConfig"
   echo "metadata:"
   echo "  name: ${CLUSTER_NAME}"
   echo "rendezvousIP: ${base_ip}.20"
   echo "hosts:"
-  
   # Generate master nodes configurations
   for i in {1..3}; do
     local ip=$((20+i))
@@ -408,11 +416,19 @@ generate_install_config() {
 
   local base_domain=${DOMAIN_NAME}
   local cluster_name=${CLUSTER_NAME}
-  local api_vip=$(grep 'api.'${cluster_name}'.'${base_domain} /etc/hosts | awk '{print $1}')
-  local ingress_vip=$(grep 'ingress.'${cluster_name}'.'${base_domain} /etc/hosts | awk '{print $1}')
-  local pull_secret=$(jq -c . $HOME/.docker/config.json)
-  local trust_bundle=$(cat ${SSL_CERT_DIR}/rootCA.pem | sed 's/^/  /')
-  
+  local api_vip=$(getent hosts "api.${cluster_name}.${base_domain}" | awk '{ print $1 }')
+
+  # Check if the api_vip is empty or not resolved
+  if [ -z "${api_vip}" ]; then
+    echo "Failed to resolve API VIP DNS for api.${cluster_name}.${base_domain}. Please verify DNS configuration."
+    exit 1
+  fi
+
+  local ingress_vip=$(getent hosts "demo.apps.${cluster_name}.${base_domain}" | awk '{ print $1 }')
+  local pull_secret=$(jq -c . $HOME/pull-secret.txt)
+  local trust_bundle=$(cat ${SSL_CERT_DIR}/rootCA.pem | sed 's/^/    /')
+  local machine_network_cidr=$(echo "${api_vip}" | awk -F '.' '{print $1"."$2"."$3".0/24"}')
+
   echo "apiVersion: v1"
   echo "baseDomain: ${base_domain}"
   echo "metadata:"
@@ -422,7 +438,7 @@ generate_install_config() {
   echo "  - cidr: 10.128.0.0/14"
   echo "    hostPrefix: 23"
   echo "  machineNetwork:"
-  echo "  - cidr: 192.168.10.0/24"
+  echo "  - cidr: ${machine_network_cidr}"
   echo "  networkType: OVNKubernetes"
   echo "  serviceNetwork:"
   echo "  - 172.30.0.0/16"
